#ifndef __ERROR_CODES_H__
#define __ERROR_CODES_H__

enum RUNET_ERROR_CODES {
  SUCCESS_CODE = 1,
  INVALID_MATRIX_INDEX_ACCESS = -101,

  INCOMPATIBLE_MATRIX_SHAPES = -201,
  EMPTY_MATRIX = -202
};

#endif // __ERROR_CODES_H__
