#ifndef __ERROR_CODES_H__
#define __ERROR_CODES_H__

enum RunetStatusCode {
  SUCCESS_CODE = 1,
  INVALID_MATRIX_INDEX_ACCESS = -101,

  INCOMPATIBLE_MATRIX_SHAPES = -201,
  NULL_PARAMETER = -202,
  MATRIX_ALLOCATION_FAILED = -203,

  SHAPE_MISMATCH = -301,
  NETWORK_AT_CAPACITY = -302,
  FILE_OPEN_ERROR = -303,
  INVALID_FILE_FORMAT = -304
};

#endif // __ERROR_CODES_H__
