#ifndef __ERROR_CODES_H__
#define __ERROR_CODES_H__

enum RunetStatusCode {
  SUCCESS_CODE = 1,
  INVALID_MATRIX_INDEX_ACCESS = -101,

  INCOMPATIBLE_MATRIX_SHAPES = -201,
  NULL_PARAMETER = -202,
};

#endif // __ERROR_CODES_H__
